Fix compiler issue with GCC 4.9.4 (from op-build)
GCC 4.9.4 is used in op-build and barfs currently with:

	[CC]  hw/lpc-uart.o
hw/lpc-uart.c: In function ‘uart_setup_os_passthrough’:
hw/lpc-uart.c:428:2: error: missing initializer for field ‘reset’ of ‘struct lpc_client’ [-Werror=missing-field-initializers]
  };

This fixes it.

Signed-off-by: Michael Neuling <mikey@neuling.org>