ci: Remove Centos 8
With Centos 8 gone "EOL", the Centos 8 repositories have been moved(!)
causing the build to fail:

 Step 2/14 : RUN yum -y update && yum clean all
  ---> Running in 49e78cad4cda
 CentOS Linux 8 - AppStream                      424  B/s |  38  B     00:00
 Error: Failed to download metadata for repo 'appstream': Cannot prepare
 internal mirrorlist: No URLs in mirrorlist

Remove the build from CI as it no longer works.

Signed-off-by: Joel Stanley <joel@jms.id.au>
Reviewed-by: Dan Horák <dan@danny.cz>
Signed-off-by: Cédric Le Goater <clg@kaod.org>