pau: Fix a build error with GCC 13.1.1
Compiling hmi.c with GCC 13.1.1 results in following error

core/hmi.c:860:25: error: ‘pau’ may be used uninitialized [-Werror=maybe-uninitialized]
  860 |                         pau_opencapi_dump_scoms(pau);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix this by initializing variable 'pau' with NULL when defined in
npu_fir_errors(). Variable 'pau' is only assigned/referenced in switch-case
blocks when phb_type == phb_type_pau_opencapi. Hence this patch shouldn't
introduce any behavioral changes.

Signed-off-by: Vaibhav Jain <vaibhav@linux.ibm.com>
Signed-off-by: Reza Arbab <arbab@linux.ibm.com>