mambo: print useful error when mysim mmap fails
My user id didn't have access to disk.img and the code printed
the error message:

ERROR: pmem: 'mysim mmap' command needs newer mambo

mysim mmap has been in Mambo for a while so this patch prints out the
error message from catch.  Now we get the useful:

ERROR: pmem: 'mysim mmap' Error opening file disk.img for mapping

Signed-off-by: Ryan Grimm <grimm@linux.ibm.com>
Reviewed-by: Dan Horák <dan@danny.cz>
Signed-off-by: Reza Arbab <arbab@linux.ibm.com>