hdata/test: Fix broken tests
Commit e810dcbc (ATTN: Set up attention area to handle attention) broke
tests, as the familiy of CPU_TO_BEXX macros are not compile time constant.

hdata/test/../spira.c:60:4: error: initializer element is not constant
    .addr = CPU_TO_BE64((unsigned long)&(cpu_ctl_spat_area) + SKIBOOT_BASE)

There is no test coverage of this code, so for now we can comment out
these areas in order to allow the tests to pass.

Signed-off-by: Joel Stanley <joel@jms.id.au>
Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>