xive: Trivial fix for compilation error when enabling xive debug
Without this, we get:

hw/xive.c: In function ‘xive_special_cache_check’:
hw/xive.c:2982:9: error: missing initializer for field ‘w0’ of
‘struct xive_vp’ [-Werror=missing-field-initializers]

Signed-off-by: Guilherme G. Piccoli <gpiccoli@linux.vnet.ibm.com>
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>