Fix bug/warning in hdata/memory.c I introduced in f1a3a19
Passing the wrong parameter to snprintf (sizeof(char*)) rather
than actual length of the string. GCC 4.9 told us about it (and broke
make check when I enabled -Werror)

hdata/test/../memory.c: In function ‘add_address_range’:

hdata/test/../memory.c:144:23: error: argument to ‘sizeof’ in ‘snprintf’ call is the same expression as the destination; did you mean to provide an explicit length? [-Werror=sizeof-pointer-memaccess]

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>