hdata/i2c.c: fix building with gcc8
[ Upstream commit 70d544de8739abbc381398cbfd07a6bd6dc8c1a5 ]

hdata/test/../i2c.c:200:1: error: alignment 1 of ‘struct host_i2c_hdr’ is less than 4 [-Werror=packed-not-aligned]
 } __packed;
 ^

Fixes: https://github.com/open-power/skiboot/issues/160
Signed-off-by: Stewart Smith <stewart@linux.ibm.com>
Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>