GCOV: Fix compilation error
On gcc v4.9.2 we are hitting below error.

[ HOSTCC ] extract-gcov.c
In file included from /usr/include/stdint.h:25:0,
	from /usr/lib/gcc/x86_64-redhat-linux/4.9.2/include/stdint.h:9,
	from /data/opensource/pkvm/skiboot/ccan/short_types/short_types.h:4,
	from extract-gcov.c:18:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
# warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
							      ^
cc1: all warnings being treated as errors
/data/opensource/pkvm/skiboot/Makefile.main:179: recipe for target 'extract-gcov' failed

>From features.h header file:
  /* _BSD_SOURCE and _SVID_SOURCE are deprecated aliases for
  _DEFAULT_SOURCE.  If _DEFAULT_SOURCE is present we do not
  issue a warning; the expectation is that the source is being
  transitioned to use the new macro.  */

Hence replace _BSD_SOURCE with _DEFAULT_SOURCE.

Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>
CC: Stewart Smith <stewart@linux.vnet.ibm.com>
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>