devicetree: Fix syntax error in power9-phb4.dts
Remove the extra space causing this:

  Error: power9-phb4.dts:156.15-16 syntax error
  FATAL ERROR: Unable to parse input tree

Signed-off-by: Reza Arbab <arbab@linux.ibm.com>
Signed-off-by: Stewart Smith <stewart@linux.ibm.com>