travis: allow failures of fedora24
Because Fedora repositories are unreliable and we often get:
  Error: Failed to synchronize cache for repo 'updates'

:(

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>