print-stb-container: Fix build on centos7
Because of ordering of include files, we got:

/usr/include/bits/stat.h:106:31: error: expected identifier or '(' before '[' token
     __syscall_slong_t __unused[3];

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>