libflash/ipmi-hiomap: Fix argument type warning on x86-64
[ Upstream commit 97f839beffb512faebc456dff67a4d83353348ed ]

libflash/ipmi-hiomap.c: In function ‘hiomap_window_move’:
libflash/ipmi-hiomap.c:17:21: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
 #define pr_fmt(fmt) "HIOMAP: " fmt
                     ^~~~~~~~~~
include/skiboot.h:93:41: note: in expansion of macro ‘pr_fmt’
 #define prlog(l, f, ...) do { _prlog(l, pr_fmt(f), ##__VA_ARGS__); } while(0)
                                         ^~~~~~
include/skiboot.h:94:30: note: in expansion of macro ‘prlog’
 #define prerror(fmt...) do { prlog(PR_ERR, fmt); } while(0)
                              ^~~~~
libflash/ipmi-hiomap.c:291:3: note: in expansion of macro ‘prerror’
   prerror("Invalid window properties: len: %llu, size: %llu\n",
   ^~~~~~~
libflash/ipmi-hiomap.c:291:47: note: format string is defined here
   prerror("Invalid window properties: len: %llu, size: %llu\n",
                                            ~~~^
                                            %lu

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Signed-off-by: Stewart Smith <stewart@linux.ibm.com>