specfile: Fix build issues
We have "%{?_smp_mflags}" in specfile. This will initiate multiple jobs.
In some cases (like opal-prd), we have to first create symbolic link
and then start compilation. Because of multiple jobs created by make,
we hit below error.

ln -sfr ../../ccan ./ccan
ln -sfr ../common ./common
ln -sfr ../../libflash ./libflash
make: *** No rule to make target 'libflash/blocklevel.c', needed by 'libflash-blocklevel.o'.  Stop.
make: *** Waiting for unfinished jobs....
make: Leaving directory '/root/rpmbuild/BUILD/skiboot-skiboot-5.1.13/external/opal-prd'
error: Bad exit status from /var/tmp/rpm-tmp.ZG2RS6 (%build)

This patch removes "%{?_smp_mflags}" from specfile.

Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>
CC: Cédric Le Goater <clg@fr.ibm.com>
Acked-by: Cedric Le Goater <clg@fr.ibm.com>
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>