hdata/tests/stubs.c: fix GCC8 warning
[ Upstream commit f708f67a4d0a2465376b9b7e2a84b71e195172e4 ]

hdata/test/stubs.c:112:11: error: ‘lock_caller’ alias between functions of incompatible types ‘void(void)’ and ‘_Bool(void)’ [-Werror=attribute-alias]
 NOOP_STUB(lock_caller);
           ^~~~~~~~~~~

We fix it by giving the correct prototype to our stub

Signed-off-by: Stewart Smith <stewart@linux.ibm.com>