libstb: Fix build in OpenSSL 1.1
OpenSSL has some API changes which causes a build break in libstb.
Specifically, directly accessing some members of a signature now requires using
a helper.

This fixes things in OpenSSL 1.1 and has no effect on OpenSSL 1.0.

The build failure was as follows:

[ HOSTCC ] libstb/create-container.c
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/ec.h:30,
                 from libstb/create-container.c:36:
libstb/create-container.c: In function ‘getSigRaw’:
libstb/create-container.c:104:31: error: dereferencing pointer to incomplete
				  type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
  rlen = BN_num_bytes(signature->r);
                               ^

Signed-off-by: Russell Currey <ruscur@russell.cc>
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>