github: Run update before installing packages
The Github CI runners sometimes need to update their apt cache, or
packages fail to install:

 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-9-cross/gcc-9-powerpc64le-linux-gnu_9.3.0-17ubuntu1~20.04cross2_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
 Error: Process completed with exit code 100.

Signed-off-by: Joel Stanley <joel@jms.id.au>
Signed-off-by: Cédric Le Goater <clg@kaod.org>