doc/requirements.txt: pin docutils at 0.14
[ Upstream commit 8995ad6165b4a1518f3efd5a48ca5a8cd0be6b4b ]

docutils is a dependency for sphinx. The recently released 0.15 version
throws a syntax error like so:

+ cd doc
+ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 6, in <module>
    from sphinx.cmd.build import main
  File "/usr/lib64/python2.7/site-packages/sphinx/cmd/build.py", line 20, in <module>
    from docutils.utils import SystemMessage
  File "/usr/lib/python2.7/site-packages/docutils/utils/__init__.py", line 21, in <module>
    import docutils.io
  File "/usr/lib/python2.7/site-packages/docutils/io.py", line 348
    (self.destination.mode, mode)), file=self._stderr)
                                        ^
SyntaxError: invalid syntax
make: *** [Makefile:53: html] Error 1

obviously, this isn't ideal - so let's pin our version to one that
actually works.

Signed-off-by: Stewart Smith <stewart@linux.ibm.com>
Signed-off-by: Oliver O'Halloran <oohall@gmail.com>
Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>