core/pldm: Fix unused-but-set-variable error
Newer GCC are catching this:

  core/pldm/pldm-file-io-requests.c: In function 'write_file_req':
  core/pldm/pldm-file-io-requests.c:252:30: error: variable 'current_ptr' set but not used [-Werror=unused-but-set-variable=]
    252 |         void *response_msg, *current_ptr, *payload_data;
        |                              ^~~~~~~~~~~

Signed-off-by: Reza Arbab <arbab@linux.ibm.com>