struct p9_sbe_msg doesn't need to be packed
[ Upstream commit ef691db3533742d9dd6eed1a311472a7c52be94b ]

Only the reg member is sent anywhere (via xscom_write), so the structure
does not need to be packed.

Fixes GCC9 build problem:
hw/sbe-p9.c: In function ‘p9_sbe_msg_send’:
hw/sbe-p9.c:270:9: error: taking address of packed member of ‘struct p9_sbe_msg’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  270 |  data = &msg->reg[0];
      |         ^~~~~~~~~~~~

Signed-off-by: Stewart Smith <stewart@linux.ibm.com>
Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>