hdata/spira.c: fix iplparams feature name string handling
[ Upstream commit 44d0f8638bc1d35baccd59a154298fef0fb51775 ]

Fixes this gcc8 warning:

hdata/test/../spira.c: In function ‘add_iplparams_features’:
hdata/test/../spira.c:1209:38: error: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]
   strncpy(name, feature->name, sizeof(feature->name));
                                      ^
Signed-off-by: Stewart Smith <stewart@linux.ibm.com>

Signed-off-by: Stewart Smith <stewart@linux.ibm.com>