core/test/run_mem_region: fix GCC8 compile error
[ Upstream commit b32ddeb7ea0de77864e463260c6bb1543e39fe78 ]

error: ‘const’ attribute on function returning ‘void’ [-Werror=attributes]

Fix by not putting the const attribute in the stub

Signed-off-by: Stewart Smith <stewart@linux.ibm.com>